### ISSUE TITLE
Bit rot?

### ISSUE THREAD

**Issue by plaes** [agiil/sonastik#1]
Kas kõduma taha saaks kirjutada ka bit roti?

https://en.wikipedia.org/wiki/Software_rot

**Comment by PriitParmakson** [comment]
Aitäh ettepaneku ja viite eest! "Semantic rot" kargas ka mulle just neil päevil pähe. Eesti keeles on päris paras hulk sõnu seistes halvaks minemise kohta. Lisasin ettepanek-sõnadena https://agiil.github.io/sonastik/#andmelapastumine ja https://agiil.github.io/sonastik/#semantilineraasumine, aga eks hea eestikeelne vaste (või vasted) peavad alles välja kujunema.

**Comment by plaes** [comment]
See, mis juba praegu kirja sai on super :)
